### ISSUE TITLE
add support for plexV9 +

### ISSUE THREAD

**Issue by roest01** [cytec/Sick-Beard#64]
> In Plex v8,  the URL pattern was something like:
http://PLEX-IP:3000/xbmcCmds/xbmcHttp?command=ExecBuiltIn&parameter=XBMC.updatelibrary(video)

> And in Plex v9, I think the URL pattern is:
http://PMS-IP:32400/library/sections/[x]/refresh[?force=1]

[Source](https://forums.plex.tv/index.php/topic/25047-sickbeard-now-supports-plex-notifications-and-library-updates/#entry158956)

```
Jan-31 17:15:07 ERROR    CP Server Thread-3 :: Error while trying to contact Plex Media Server: socket error
```

![nas-plex_contact_error](https://cloud.githubusercontent.com/assets/2870718/5988815/562285fc-a970-11e4-8a77-67a6b4308945.png)

**Comment by roest01** [comment]
cloud be irrelevant because of confusing test button. xbmcCmds can be the protocol of the client ?

**Comment by cytec** [comment]
I don't really have a clue sorry...
i can change the url which is called when Plex is notified... but i don't know which is the right URL or which args it would take...

if you provide that info i implement it
